-- AlterTable
ALTER TABLE `PageToken` MODIFY `platform` ENUM('ALL', 'YOUTUBE', 'TIKTOK', 'GOOGLE', 'MEDIUM', 'PINTEREST', 'QUORA', 'REDDIT', 'LINKEDIN', 'TWITTER', 'FACEBOOK', 'INSTAGRAM', 'ZOHO_WORKDRIVE') NOT NULL DEFAULT 'FACEBOOK';

-- AlterTable
ALTER TABLE `Post` MODIFY `platform` ENUM('ALL', 'YOUTUBE', 'TIKTOK', 'GOOGLE', 'MEDIUM', 'PINTEREST', 'QUORA', 'REDDIT', 'LINKEDIN', 'TWITTER', 'FACEBOOK', 'INSTAGRAM', 'ZOHO_WORKDRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `SocialAccount` MODIFY `platform` ENUM('ALL', 'YOUTUBE', 'TIKTOK', 'GOOGLE', 'MEDIUM', 'PINTEREST', 'QUORA', 'REDDIT', 'LINKEDIN', 'TWITTER', 'FACEBOOK', 'INSTAGRAM', 'ZOHO_WORKDRIVE') NOT NULL;
