import { generateImage as generateGeminiImage } from '@/lib/gemini';
import cloudinary from '@/lib/cloudinary';
import { getToken } from 'next-auth/jwt';
import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
    const token = await getToken({ req });
    if (!token?.id) {
        return NextResponse.redirect(new URL("/login", req.url));
    }

    try {
        const data = await req.json();
        const { prompt, aspectRatio = '1:1' } = data;

        if (!prompt) {
            return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
        }

        const response = await generateImage(prompt, aspectRatio);
        
        if (!response) {
            return NextResponse.json({ error: "Failed to generate image" }, { status: 500 });
        }

        return NextResponse.json(response, { status: 200 });
    } catch (error) {
        console.error("Error in POST handler:", error);
        return NextResponse.json({ 
            error: "Internal server error",
            details: error instanceof Error ? error.message : "Unknown error"
        }, { status: 500 });
    }
}

async function generateImage(prompt: string, aspectRatio: string = '1:1') {
    try {
        console.log('Generating image with Gemini (latest API)...');
        
        // Enhanced prompt for better social media images
        const enhancedPrompt = `Create a high-quality, professional, visually appealing image for social media posting. 
        Style: Modern, clean, eye-catching, suitable for ${aspectRatio} aspect ratio.
        Description: ${prompt}
        
        The image should be:
        - High resolution and sharp
        - Well-composed with good lighting
        - Suitable for social media platforms (Facebook, Instagram, LinkedIn, Twitter)
        - Engaging and attention-grabbing
        - Professional quality
        - Vibrant colors and clear details`;

        // Generate image using Gemini's latest API
        const result = await generateGeminiImage(enhancedPrompt, {
            aspectRatio: aspectRatio as any,
            numberOfImages: 1
        });

        if (!result.images || result.images.length === 0) {
            throw new Error("No image generated by Gemini");
        }

        const imageBase64 = result.images[0];
        console.log("Image generated successfully with Gemini (gemini-3-pro-image-preview)");
        console.log("Generated text:", result.text);

        // Upload to Cloudinary
        const base64Data = `data:image/png;base64,${imageBase64}`;
        
        const uploadResult = await cloudinary.uploader.upload(base64Data, {
            folder: "ai-generated-images",
            quality: "auto",
            fetch_format: "auto",
            transformation: [
                { quality: "auto:best" },
                { fetch_format: "auto" }
            ]
        });

        const imageUrl = uploadResult.secure_url;
        console.log("Image uploaded to Cloudinary:", imageUrl);
        
        return {
            imageUrl,
            imageBase64,
            provider: 'gemini-3-pro-image',
            aspectRatio,
            description: result.text || 'Image generated successfully'
        };
        
    } catch (error) {
        console.error("Error generating image with Gemini:", error);
        
        // Log detailed error information
        if (error instanceof Error) {
            console.error("Error details:", error.message);
            console.error("Error stack:", error.stack);
        }
        
        return null;
    }
}